server:
  port: 8080
  servlet:
    context-path: /client2
 
client2.message: "I am client2"
demo.message: "Test message Refreshed for client 2 from local"
management.endpoints.web.exposure.include: "*"